Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerWebsite.Models
{
    public class Message
    {
        public String content { get; set; }

        public Message(String content)
        {
            this.content = content;
        }
    }
}

Models/SystemAdmin.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerWebsite.Models
{
    public class SystemAdmin : SystemUser
    {
        public SystemAdmin(string username, string password) : base(username, password)
        {

        }
        public SystemAdmin()
        {

        }
    }
}

Controllers/SystemAdminController.cs
using SoccerWebsite.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml.Linq;

namespace SoccerWebsite.Controllers
{
    public class SystemAdminController : Controller
    {
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Soccer"].ToString());

        // GET: SystemAdmin
        public ActionResult Index()
        {
            return View();
        }


        public ActionResult Login()
        {
            return View();
        }



        public ActionResult AddClub()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }



        public ActionResult DeleteClub()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }

        

        public ActionResult AddStadium()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }



        public ActionResult DeleteStadium()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }



        public ActionResult BlockFan()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }


        public ActionResult UnblockFan()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }


        public ActionResult AllClubs()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            List<Club> clubs = getAllClubs();

            return View("AllClubs", clubs);
        }


        public ActionResult AllStadiums()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            List<Stadium> stadiums = getAllStadiums();

            return View("AllStadiums", stadiums);
        }


        public ActionResult AllFans()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            List<Fan> fans = getAllFans();

            return View("AllFans", fans);
        }



        public ActionResult Message()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }
        public List<Club> getAllClubs()
        {
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from Club";

            SqlDataReader dr = cmd.ExecuteReader();

            List<Club> allClubs = new List<Club>();

            while (dr.Read())
            {
                Club club = new Club(dr["name"].ToString(), dr["location"].ToString());

                allClubs.Add(club);
            }
            connection.Close();

            return allClubs;
        }


        public List<Stadium> getAllStadiums()
        {
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from Stadium";

            SqlDataReader dr = cmd.ExecuteReader();

            List<Stadium> allStadiums = new List<Stadium>();

            while (dr.Read())
            {
                Stadium stad = new Stadium(dr["name"].ToString(), dr["location"].ToString(), dr["capacity"].ToString());

                allStadiums.Add(stad);
            }
            connection.Close();

            return allStadiums;
        }



        public List<Fan> getAllFans()
        {
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from Fan";

            SqlDataReader dr = cmd.ExecuteReader();

            List<Fan> allFans = new List<Fan>();

            while (dr.Read())
            {
                String status;
                
                if (dr["status"].ToString().Equals("True"))
                    status = "Allowed";
                else
                    status = "Blocked";

                Fan fan = new Fan(dr["name"].ToString(), dr["username"].ToString(), dr["national_id"].ToString(), dr["phone_number"].ToString(), dr["address"].ToString(), dr["birth_date"].ToString(), status);

                allFans.Add(fan);
            }
            connection.Close();

            return allFans;
        }




        [HttpPost]
        public ActionResult Login(String username, String password)
        {


            SqlCommand cmd = new SqlCommand("adminLogin", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if(result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("AdminComponents");  
            }
            else
            {
                Message msg = new Message("You are not registered, Please create an account");
                return View("Message",msg);
            }


      
        }

        [HttpPost]
        public ActionResult AddClub(String name, String location)
        {
            SqlCommand cmd = new SqlCommand("addClub", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@club_name", name));
            cmd.Parameters.Add(new SqlParameter("@location", location));

            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                List<Club> clubs = getAllClubs();

                return View("AllClubs", clubs);
            }
            else
            {
                Message msg = new Message("Club exists already");
                return View("Message", msg);
            }

            
        }


       


        [HttpPost]
        public ActionResult DeleteClub(String name)
        {
            SqlCommand cmd = new SqlCommand("deleteClub", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@club_name", name));

            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                List<Club> clubs = getAllClubs();

                return View("AllClubs", clubs);
            }
            else
            {
                Message msg = new Message("Club does not exist");
                return View("Message", msg);
            }
        }


        [HttpPost]
        public ActionResult AddStadium(String name, String location, String capacity)
        {

            
            SqlCommand cmd = new SqlCommand("addStadium", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@stadium_name", name));
            cmd.Parameters.Add(new SqlParameter("@location", location));
            cmd.Parameters.Add(new SqlParameter("@capacity", Int32.Parse(capacity)));

            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;



            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                List<Stadium> allStadiums = getAllStadiums();

                return View("AllStadiums", allStadiums);
            }
            else
            {
                Message msg = new Message("Stadium exists already");
                return View("Message", msg);
            }

        }

        [HttpPost]
        public ActionResult DeleteStadium(String name)
        {
            SqlCommand cmd = new SqlCommand("deleteStadium", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

Views/SystemAdmin/AddClub.cshtml
@{
    ViewBag.Title = "AddClub";
}

<h1>Add Club</h1>
<hr />


@using (Html.BeginForm("AddClub", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Name</label>
            <input type="text" class="form-control" id="exampleInputUsername" name="name" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">Location</label>
            <input type="text" class="form-control" id="exampleInputPassword" name="location" required>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/AddStadium.cshtml
@{
    ViewBag.Title = "AddStadium";
}

<h1>Add Stadium</h1>
<hr />


@using (Html.BeginForm("AddStadium", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="nameInput" class="form-label">Name</label>
            <input type="text" class="form-control" id="nameInput" name="name" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="locationInput" class="form-label">Location</label>
            <input type="text" class="form-control" id="locationInput" name="location" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="capacityInput" class="form-label">Capacity</label>
            <input type="number" class="form-control" id="capacityInput" name="capacity" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/AdminComponents.cshtml
@{
    ViewBag.Title = "AdminComponents";
}

<body style="font-size:20px">

    <h1>Admin Components</h1>

    <hr />

    <h2>Choose what you want to do!</h2>

    <br />

    @Html.ActionLink("Add new club", "AddClub", "SystemAdmin")

    <br />

    @Html.ActionLink("Delete an existing club", "DeleteClub", "SystemAdmin")

    <br />

    @Html.ActionLink("Add new stadium", "AddStadium", "SystemAdmin")

    <br />

    @Html.ActionLink("Delete an existing stadium", "DeleteStadium", "SystemAdmin")

    <br />

    @Html.ActionLink("Block a fan", "BlockFan", "SystemAdmin")

    <br />
    @Html.ActionLink("Unblock a fan", "UnblockFan", "SystemAdmin")

    <br />

    @Html.ActionLink("Show all clubs", "AllClubs", "SystemAdmin")

    <br />

    @Html.ActionLink("Show all Stadiums", "AllStadiums", "SystemAdmin")

    <br />

    @Html.ActionLink("Show all Fans", "AllFans", "SystemAdmin")

</body>

Views/SystemAdmin/AllClubs.cshtml
@model List<SoccerWebsite.Models.Club>


@{
    ViewBag.Title = "All Clubs";
}

<h1>All Clubs</h1>

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Location</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (SoccerWebsite.Models.Club club in Model)
        {
            <tr>
                <td>@club.name</td>
                <td>@club.location</td>
                <td>
                    <button class="btn btn-danger">@Html.ActionLink("Delete", "DeleteClub")</button>
                </td>




            </tr>
        }
    </tbody>
</table>

Views/SystemAdmin/AllFans.cshtml
@model List<SoccerWebsite.Models.Fan>

@{
    ViewBag.Title = "AllFans";
}

<h1>All Fans</h1>

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Username</th>
            <th scope="col">National ID</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Address</th>
            <th scope="col">Birth Date</th>
            <th scope="col">Status</th>
            <th scope="col">Block Fan</th>
            <th scope="col">Unblock Fan</th>


        </tr>
    </thead>
    <tbody>
        @foreach (SoccerWebsite.Models.Fan fan in Model)
        {
            <tr>
                <td>@fan.name</td>
                <td>@fan.username</td>
                <td>@fan.nationalId</td>
                <td>@fan.phoneNumber</td>
                <td>@fan.address</td>
                <td>@fan.birthDate</td>
                <td>@fan.status</td>

                <td>
                    <button class="btn btn-danger">@Html.ActionLink("Block", "BlockFan")</button>
                </td>

                <td>
                    <button class="btn btn-success">@Html.ActionLink("Unblock", "UnblockFan")</button>
                </td>

            </tr>
        }
    </tbody>
</table>

Views/SystemAdmin/AllStadiums.cshtml
@model List<SoccerWebsite.Models.Stadium>


@{
    ViewBag.Title = "All Stadiums";
}

<h1>All Stadiums</h1>

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Location</th>
            <th scope="col">Capacity</th>
            <th scope="col">Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (SoccerWebsite.Models.Stadium stadium in Model)
        {
            <tr>
                <td>@stadium.stadName</td>
                <td>@stadium.location</td>
                <td>@stadium.capacity</td>
                <td>
                    <button class="btn btn-danger">@Html.ActionLink("Delete", "DeleteStadium")</button>
                </td>




            </tr>
        }
    </tbody>
</table>

Views/SystemAdmin/BlockFan.cshtml
@{
    ViewBag.Title = "BlockFan";
}

<h1>BlockFan</h1>

<hr />

@using (Html.BeginForm("BlockFan", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="idInput" class="form-label">National ID Number</label>
            <input type="text" class="form-control" id="idInput" name="nationalId" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/DeleteClub.cshtml
@{
    ViewBag.Title = "DeleteClub";
}

<h1>Delete Club</h1>

<hr />

@using (Html.BeginForm("DeleteClub", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Name</label>
            <input type="text" class="form-control" id="exampleInputUsername" name="name" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/DeleteStadium.cshtml
@{
    ViewBag.Title = "DeleteStadium";
}

<h1>DeleteStadium</h1>

<hr />

@using (Html.BeginForm("DeleteStadium", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="nameInput" class="form-label">Name</label>
            <input type="text" class="form-control" id="nameInput" name="name" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h1>Login As System Admin</h1>

<hr />

@using (Html.BeginForm("Login", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="exampleInputUsername" name="username" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword" name="password" required>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SystemAdmin/Message.cshtml
@model SoccerWebsite.Models.Message

@{
    ViewBag.Title = "Message";
}



<body style="text-align:center;color:red;display:flex;justify-content:center">

    <h1 style="color:black">Something went wrong</h1>
    <br />
    <div style="border:2px solid red;padding:20px 20px 50px 20px">
        <h2>@Model.content</h2>
    </div>

</body>

Views/SystemAdmin/UnblockFan.cshtml
@{
    ViewBag.Title = "Unblock Fan";
}

<h1>BlockFan</h1>

<hr />

@using (Html.BeginForm("UnblockFan", "SystemAdmin", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="idInput" class="form-label">National ID Number</label>
            <input type="text" class="form-control" id="idInput" name="nationalId" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}