Controllers/ClubRepController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using SoccerWebsite.Models;
using System.Web.Http.Results;

namespace SoccerWebsite.Controllers
{
    public class ClubRepController : Controller
    {
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Soccer"].ToString());

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();           
        }

        public ActionResult Register()
        {
            return View();
        }

        public ActionResult InputDate() 
        {
            if(Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }

            return View();
        }

        public ActionResult SendRequest()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();  
        }

        public ActionResult ShowRepsData()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }

            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from getAllClubReps";

            SqlDataReader dr = cmd.ExecuteReader();

            List<ClubRep> allClubReps = new List<ClubRep>();

            while (dr.Read())
            {
                ClubRep clubRep = new ClubRep(dr["repName"].ToString(), dr["clubName"].ToString(), dr["location"].ToString());

                allClubReps.Add(clubRep);
            }
            connection.Close();

            return View(allClubReps);
        }


        public ActionResult ShowManagersData()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from getAllStadiumManagers";

            SqlDataReader dr = cmd.ExecuteReader();

            List<StadiumManager> stadManagers = new List<StadiumManager>();

            while (dr.Read())
            {
                StadiumManager stadMan = new StadiumManager(dr["manName"].ToString(), dr["stadName"].ToString(), dr["location"].ToString());

                stadManagers.Add(stadMan);
            }
            connection.Close();

            return View(stadManagers);
        }

        public ActionResult AllHostRequest()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }

            connection.Open();

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from getSystemRequests";

            SqlDataReader dr = cmd.ExecuteReader();

            List<HostRequest> allHostRequest = new List<HostRequest>();

            while (dr.Read())
            {
                String status;

                if (dr["status"].ToString().Equals("True"))
                    status = "Accepted";
                else if (dr["status"].ToString().Equals("False"))
                    status = "Rejected";
                else
                    status = "Unhandled";

                HostRequest hostRequest = new HostRequest(dr["senderName"].ToString(), dr["hostName"].ToString(), dr["guestName"].ToString(), dr["starts"].ToString(), dr["ends"].ToString(), status);

                allHostRequest.Add(hostRequest);
            }

            connection.Close();
            return View("AllHostRequest",allHostRequest);

        }


        [HttpPost]
        public ActionResult Login(String username, String password)
        {


            SqlCommand cmd = new SqlCommand("clubRepLogin", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("ClubRepComponents");
            }
            else
            {
                Message msg = new Message("You are not registered, Please create an account");
                return View("Message", msg);
            }



        }

        [HttpPost]
        public ActionResult Register(String repName, String clubName, String username, String password)
        {
            SqlCommand cmd = new SqlCommand("addRepresentative", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@rep_name", repName));
            cmd.Parameters.Add(new SqlParameter("@club_name", clubName));
            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));



            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("ClubRepComponents");
            }
            else
            {
                Message msg = new Message("There is a user exists already with that username");
                return View("Message", msg);
            }
        }

        public ActionResult ViewClubData()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            SqlCommand cmd = new SqlCommand("getClubName", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@repUsername", Session["newUser"].ToString()));

            SqlParameter result = cmd.Parameters.Add("@clubName", SqlDbType.NVarChar,20);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();

            SqlCommand cmd2 = new SqlCommand();
            cmd2.Connection = connection;
            cmd2.CommandText = "select * from Club where name =" + "'" + result.Value.ToString() + "'";

            SqlDataReader dr = cmd2.ExecuteReader();

            List<Club> allClubs = new List<Club>();

            while (dr.Read())
            {
                Club club = new Club(dr["name"].ToString(), dr["location"].ToString());

                allClubs.Add(club);
            }
            connection.Close();
            return View("ClubInfo", allClubs);

          }

        public ActionResult UpcomingMatches()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }

            SqlCommand cmd = new SqlCommand("getClubName", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@repUsername", Session["newUser"].ToString()));

            SqlParameter result = cmd.Parameters.Add("@clubName", SqlDbType.NVarChar, 20);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();

            SqlCommand cmd2 = new SqlCommand();
            cmd2.Connection = connection;
            cmd2.CommandText = "select * from dbo.upcomingMatchesOfClub('" + result.Value.ToString() + "')" ;

            SqlDataReader dr = cmd2.ExecuteReader();

            List<Match> allMatches = new List<Match>();

            while (dr.Read())
            {
                Match match = new Match(dr["firstClub"].ToString(), dr["secondClub"].ToString(), dr["starts"].ToString(), dr["ends"].ToString(), dr["stadName"].ToString(),null);

                allMatches.Add(match);
            }

            connection.Close();
            return View("UpcomingMatches", allMatches);

        }

        [HttpPost]
        public ActionResult AvailableStadiumsOn(String date)
        {

            try
            {
                if (!(date[2].ToString().Equals("/") && date[5].ToString().Equals("/")) || date.Length != 10)
                {
                    Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                    return View("Message", msg);
                }
                else
                {
                    int month = Int32.Parse(date[0] + "" + date[1]);
                    int day = Int32.Parse(date[3] + "" + date[4]);

                    if (month > 12 || month < 1 || day > 30 || day < 1)
                    {
                        Message msg = new Message("Please enter a valid date format Month/Day/Year");
                        return View("Message", msg);
                    }

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SoccerWebsite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult Register()
        {
            return View();
        }


    }
}

Controllers/StadiumManagerController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using SoccerWebsite.Models;
using System.Web.Http.Results;

namespace SoccerWebsite.Controllers
{
    public class StadiumManagerController : Controller
    {
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Soccer"].ToString());

        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }


        


        


        [HttpPost]
        public ActionResult Login(String username, String password)
        {


            SqlCommand cmd = new SqlCommand("stadManLogin", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("StadiumManagerComponents");
            }
            else
            {
                Message msg = new Message("You are not registered, Please create an account");
                return View("Message", msg);
            }



        }

        [HttpPost]
        public ActionResult Register(String name,  String username, String password,String stadiumName)
        {
            SqlCommand cmd = new SqlCommand("addStadiumManager", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@manager_name", name));
            cmd.Parameters.Add(new SqlParameter("@stadium_name", stadiumName));
            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));



            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("StadiumManagerComponents");
            }
            else
            {
                Message msg = new Message("There is a user exists already with that username");
                return View("Message", msg);
            }
        }

        public ActionResult ViewStadiumData()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            SqlCommand cmd = new SqlCommand("getStadName", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@manUsername", Session["newUser"].ToString()));

            SqlParameter result = cmd.Parameters.Add("@stadName", SqlDbType.NVarChar,20);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();

            SqlCommand cmd2 = new SqlCommand();
            cmd2.Connection = connection;
            cmd2.CommandText = "select * from Stadium where name =" + "'" + result.Value.ToString() + "'";

            SqlDataReader dr = cmd2.ExecuteReader();

            List<Stadium> allStadium = new List<Stadium>();

            while (dr.Read())
            {
                Stadium stadium = new Stadium(dr["name"].ToString(), dr["location"].ToString(), dr["capacity"].ToString());

                allStadium.Add(stadium);
            }
            connection.Close();
            return View("ViewStadiumData", allStadium);

          }

        public ActionResult AllHostRequest()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            connection.Open();  

            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from dbo.getAllRequests('" + Session["newUser"].ToString() + "')" ;

            SqlDataReader dr = cmd.ExecuteReader();

            List<HostRequest> allHostRequest = new List<HostRequest>();

            while (dr.Read())
            {
                String status;

                if (dr["status"].ToString().Equals("True"))
                    status = "Accepted";
                else if (dr["status"].ToString().Equals("False"))
                    status = "Rejected";
                else
                    status = "Unhandled";
                HostRequest hostRequest = new HostRequest(dr["senderName"].ToString(), dr["hostName"].ToString(), dr["guestName"].ToString(), dr["starts"].ToString(), dr["ends"].ToString(), status);

                allHostRequest.Add(hostRequest);
            }

            connection.Close();
            return View("AllHostRequest", allHostRequest);

        }

      
        public ActionResult DetermineRequest(String hostName, String guestName,String start,int flag)
        {
            String newFormatString = start[3] +""+ start[4] + "/" + start[0] +""+ start[1] + "/" + start.Substring(6,4);
            
            String procedure;
            if (flag == 0)
                procedure = "rejectRequest";
            else
                procedure = "acceptRequest";

            SqlCommand cmd = new SqlCommand(procedure, connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            DateTime startTime = DateTime.ParseExact(newFormatString, "MM/dd/yyyy", null);

            cmd.Parameters.Add(new SqlParameter("@username", Session["newUser"].ToString()));
            cmd.Parameters.Add(new SqlParameter("@host_club_name", hostName));
            cmd.Parameters.Add(new SqlParameter("@guest_club_name", guestName));
            cmd.Parameters.Add(new SqlParameter("@match_time", startTime));



            connection.Open();
            cmd.ExecuteNonQuery();

            connection.Close();


          
            return RedirectToAction("AllHostRequest");
           


        }


















    }
}

Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}


<h1>Guide for the system</h1>
<hr />
<br />

<h2>System Admin</h2>
<br />

<p>
    The system admin is the one who can add or delete clubs, add or delete stadiums, add or delete and
    temporarily block fans from using the system.
</p>

<br />

<h2>Sports Association Manager</h2>
<br />

<p>
    First of all, the association manager (which has an ID and name) can manage (create, edit or delete) the
    matches that will be played by the different clubs
</p>

<br />

<h2>Matches</h2>
<br />

<p>
    Matches will be played by exactly two Clubs. One of them is considered the host of the match. Each
    game has an ID, starting time,
</p>



<br />

<h2>Clubs</h2>
<br />

<p>
    Each club (which has an ID, name and location) can play many matches through the season. The club
    will also have a representative (with a name and ID). who will be responsible for asking for the permission
    to host the matches played by the club he is representing when the club is the host of that match.
</p>





<br />

<h2>Stadiums</h2>
<br />

<p>
    Stadiums (which have an ID, name, capacity, location and status) are there to host the games. The status
    of the stadium can be either available or not available. Each stadium has a manager (who has a name and
    ID) who is in charge for approving or disapproving the different club requests for hosting their matches
    on the stadium he is managing .
</p>






<br />

<h2>Tickets</h2>
<br />

<p>
    Once the stadium manager approves hosting a certain game, tickets will be available for the fans to buy
    and attend the game. Each ticket has an ID, a stadium where the match is hosted on and a status that
    can either be sold or available. The system keeps track about which users bought which tickets.
</p>








<br />

<h2>Fans</h2>
<br />

<p>
    Fans (who have name, national ID number, birth date, address and phone number) can buy tickets to
    attend the matches. For some cases, a fan can temporarily be blocked from using the system.
</p>

Views/Home/Contact.cshtml
@*@{
        ViewBag.Title = "Contact";
    }
    <h2>@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>*@

<h1>Contact Us</h1>
<hr />
<br />

<h2>Arwa Gad</h2>
<ul>
    <li><a>arwa.gad@student.guc.edu.eg</a></li>
</ul>
<hr />
<h2>Jana Abubakr</h2>
<ul>
    <li><a>jana.elmawla@student.guc.edu.eg</a></li>
</ul>
<hr />

<h2>Nour Ashraf</h2>
<ul>
    <li><a>nour.ibrahimmohamed@student.guc.edu.eg</a></li>
</ul>
<hr />
<h2>Ebram Fadl</h2>
<ul>
    <li><a>ebram@ntsal.com</a></li>
</ul>
<hr />

Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}



<body style="font-size:20px">

    <h1>Identify yourself</h1>
    <br />
    <br />

    @Html.ActionLink("System Admin", "Login", "SystemAdmin")
    <br />
    @Html.ActionLink("Sport Association Manager", "Login", "SportManager")
    <br />
    @Html.ActionLink("Club Representative", "Login", "ClubRep")
    <br />
    @Html.ActionLink("Stadium Manager", "Login", "StadiumManager")
    <br />

    @Html.ActionLink("Fan", "Login", "Fan")
    <br />

    @Html.ActionLink("Register As New", "Register", "Home")

</body>




@*<div class="jumbotron">
        <h1>ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
    </div>

    <div class="row">
        <div class="col-md-4">
            <h2>Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </div>
    </div>*@

Views/Home/Register.cshtml
@{
    ViewBag.Title = "Register";
}


<body style="font-size:20px">

    <h1>Register</h1>


    <br />
    <br />


    @Html.ActionLink("Sport Association Manager", "Register", "SportManager")
    <br />
    @Html.ActionLink("Fan", "Register", "Fan")
    <br />
    @Html.ActionLink("Stadium Manager", "Register", "StadiumManager")
    <br />
    @Html.ActionLink("Club Representitive", "Register", "ClubRep")

</body>