Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerWebsite.Models
{
    public class Message
    {
        public String content { get; set; }

        public Message(String content)
        {
            this.content = content;
        }
    }
}

Controllers/SportManagerController.cs
using SoccerWebsite.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Text.RegularExpressions;
using Match = SoccerWebsite.Models.Match;
using System.Web.Http.Results;

namespace SoccerWebsite.Controllers
{
    public class SportManagerController : Controller
    {
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Soccer"].ToString());

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Login()
        {
            return View();
        }

        public ActionResult Register()
        {
            return View();
        }


        public ActionResult AddNewMatch()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }

        public ActionResult DeleteMatch()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }


        public ActionResult AllMatches()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            List<Match> matches = getAllMatches();

            return View("AllMatches",matches);
        }

        public List<Match> getAllMatches()
        {
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from getAllMatches";

            SqlDataReader dr = cmd.ExecuteReader();

            List<Match> allMatches = new List<Match>();

            while (dr.Read())
            {
                String stadName;
                String location;

                if (dr["stadName"].ToString().Equals("")) {
                    stadName = "Undetermined";
                    location = "Undetermined";
                }
                else
                {
                    stadName = dr["stadName"].ToString();
                    location = dr["location"].ToString();
                }

                Match match = new Match(dr["hostName"].ToString(), dr["guestName"].ToString(), dr["starts"].ToString(), dr["ends"].ToString(), stadName, location);

                allMatches.Add(match);
            }
            connection.Close();

            return allMatches;
        }

        public List<Club> getAllClubs()
        {
            connection.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = connection;
            cmd.CommandText = "select * from Club";

            SqlDataReader dr = cmd.ExecuteReader();

            List<Club> allClubs = new List<Club>();

            while (dr.Read())
            {
                Club club = new Club(dr["name"].ToString(), dr["location"].ToString());

                allClubs.Add(club);
            }
            connection.Close();

            return allClubs;
        }

        public ActionResult AllClubs()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            List<Club> clubs = getAllClubs();

            return View("AllClubs", clubs);
        }


        [HttpPost]
        public ActionResult Login(String username, String password)
        {


            SqlCommand cmd = new SqlCommand("sportAssociacionLogin", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("SportManagerComponents");
            }
            else
            {
                Message msg = new Message("You are not registered, Please create an account");
                return View("Message", msg);
            }



        }



        [HttpPost]
        public ActionResult Register(String name, String username, String password)
        {
            SqlCommand cmd = new SqlCommand("addAssociationManager", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@manager_name", name));
            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = username;
                return View("SportManagerComponents");
            }
            else
            {
                Message msg = new Message("There is a user exists already with that username");
                return View("Message", msg);
            }
        }


        [HttpPost]
        public ActionResult AddNewMatch(String hostName, String guestName, String startTime, String endTime)
        {
            try
            {
                if ((!(startTime[2].ToString().Equals("/") && startTime[5].ToString().Equals("/")) || startTime.Length != 10 ) || (!(endTime[2].ToString().Equals("/") && endTime[5].ToString().Equals("/")) || endTime.Length != 10))
                {
                    Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                    return View("Message", msg);
                }
                else
                {
                    int monthStart = Int32.Parse(startTime[0] + "" + startTime[1]);
                    int dayStart = Int32.Parse(startTime[3] + "" + startTime[4]);

                    int monthEnd = Int32.Parse(endTime[0] + "" + endTime[1]);
                    int dayEnd = Int32.Parse(endTime[3] + "" + endTime[4]);

                    if (monthStart > 12 || monthStart < 1 || dayStart > 30 || dayStart < 1 || monthEnd > 12 || monthEnd < 1 || dayEnd > 30 || dayEnd < 1)
                    {
                        Message msg = new Message("Please enter a valid date format Month/Day/Year");
                        return View("Message", msg);
                    }
                }
            }
            catch(Exception e)
            {
                Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                return View("Message", msg);
            }
            //String newFormatString = startTime[3] + "" + startTime[4] + "/" + startTime[0] + "" + startTime[1] + "/" + startTime.Substring(6, 4);
            //String newFormatStringEnd = endTime[3] + "" + endTime[4] + "/" + endTime[0] + "" + endTime[1] + "/" + endTime.Substring(6, 4);

            SqlCommand cmd = new SqlCommand("addNewMatch", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            DateTime start = DateTime.ParseExact(startTime, "MM/dd/yyyy", null);
            DateTime end = DateTime.ParseExact(endTime, "MM/dd/yyyy", null);



            cmd.Parameters.Add(new SqlParameter("@host_name", hostName));
            cmd.Parameters.Add(new SqlParameter("@guest_name", guestName));
            cmd.Parameters.Add(new SqlParameter("@start_time", start));
            cmd.Parameters.Add(new SqlParameter("@end_time", end));

            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();


            if (result.Value.ToString().Equals("1"))
            {
                List<Match> allMatches = getAllMatches();

                return View("AllMatches",allMatches);
            }
            else
            {
                Message msg = new Message("There is a match exists already with the same data or no clubs with the chosen names");
                return View("Message", msg);
            }


        }



        [HttpPost]
        public ActionResult DeleteMatch(String hostName, String guestName, String startTime, String endTime)
        {
            try
            {
                if ((!(startTime[2].ToString().Equals("/") && startTime[5].ToString().Equals("/")) || startTime.Length != 10) || (!(endTime[2].ToString().Equals("/") && endTime[5].ToString().Equals("/")) || endTime.Length != 10))
                {
                    Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                    return View("Message", msg);
                }
                else
                {
                    int monthStart = Int32.Parse(startTime[0] + "" + startTime[1]);
                    int dayStart = Int32.Parse(startTime[3] + "" + startTime[4]);

                    int monthEnd = Int32.Parse(endTime[0] + "" + endTime[1]);
                    int dayEnd = Int32.Parse(endTime[3] + "" + endTime[4]);

Views/SportManager/AddNewMatch.cshtml
@{
    ViewBag.Title = "AddMatch";
}

<h1>Add New Match</h1>
<hr />

@using (Html.BeginForm("AddNewMatch", "SportManager", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="inputHostName" class="form-label">Host Club Name</label>
            <input type="text" class="form-control" id="inputHostName" name="hostName" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputGuestName" class="form-label">Guest Club Name</label>
            <input type="text" class="form-control" id="inputGuestName" name="guestName" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputStart" class="form-label">Start Time</label>
            <input type="text" class="form-control" id="inputStart" placeholder="MM/DD/YYYY" name="startTime" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputEnd" class="form-label">end Time</label>
            <input type="text" class="form-control" id="inputEnd" placeholder="MM/DD/YYYY" name="endTime" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SportManager/AllClubs.cshtml
@model List<SoccerWebsite.Models.Club>


@{
    ViewBag.Title = "All clubs in the system";
}

<h1>All Clubs</h1>

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Location</th>
        </tr>
    </thead>
    <tbody>
        @foreach (SoccerWebsite.Models.Club club in Model)
        {
            <tr>
                <td>@club.name</td>
                <td>@club.location</td>
            </tr>
        }
    </tbody>
</table>

Views/SportManager/AllMatches.cshtml
@model List<SoccerWebsite.Models.Match>


@{
    ViewBag.Title = "AllMatches";
}

<h1>Matches</h1>

<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Host Club Name</th>
            <th scope="col">Guest Club Name</th>
            <th scope="col">Start Time</th>
            <th scope="col">End Time</th>
            <th scope="col">Stadium Name</th>
            <th scope="col">Location</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var match in Model)
        {
            <tr>
                <td>@match.hostName</td>
                <td>@match.guestName</td>
                <td>@match.starts</td>
                <td>@match.ends</td>
                <td>@match.stadiumName</td>
                <td>@match.location</td>
                <td>
                    <button class="btn btn-danger">@Html.ActionLink("Delete", "DeleteMatch")</button>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/SportManager/ClubsNeverMatched.cshtml
@model List<SoccerWebsite.Models.Match>


@{
    ViewBag.Title = "ClubsNeverMatched";
}

<h1>Clubs Never Matched</h1>


<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">First Club</th>
            <th scope="col">Second Club</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var match in Model)
        {
            <tr>
                <td>@match.hostName</td>
                <td>@match.guestName</td>
            </tr>
        }
    </tbody>
</table>

Views/SportManager/DeleteMatch.cshtml
@{
    ViewBag.Title = "DeleteMatch";
}

<h1>Delete Match</h1>
<hr />

@using (Html.BeginForm("DeleteMatch", "SportManager", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="inputHostName" class="form-label">Host Club Name</label>
            <input type="text" class="form-control" id="inputHostName" name="hostName" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputGuestName" class="form-label">Guest Club Name</label>
            <input type="text" class="form-control" id="inputGuestName" name="guestName" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputStart" class="form-label">Start Time</label>
            <input type="text" class="form-control" id="inputStart" placeholder="MM/DD/YYYY" name="startTime" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputEnd" class="form-label">end Time</label>
            <input type="text" class="form-control" id="inputEnd" placeholder="MM/DD/YYYY" name="endTime" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SportManager/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h1>Index</h1>

Views/SportManager/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h1>Login As SportManager</h1>

<hr />

@using (Html.BeginForm("Login", "SportManager", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="exampleInputUsername" name="username" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword" name="password" required>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SportManager/Message.cshtml
@model SoccerWebsite.Models.Message

@{
    ViewBag.Title = "Message";
}



<body style="text-align:center;color:red;display:flex;justify-content:center">

    <h1 style="color:black">Something went wrong</h1>
    <br />
    <div style="border:2px solid red;padding:20px 20px 50px 20px">
        <h2>@Model.content</h2>
    </div>

</body>

Views/SportManager/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h1>Register As Sport Association Manager</h1>
<hr />


@using (Html.BeginForm("Register", "SportManager", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="inputName" class="form-label">Name</label>
            <input type="text" class="form-control" id="inputName" name="name" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="inputUsername" name="username" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword" name="password" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/SportManager/SportManagerComponents.cshtml
@{
    ViewBag.Title = "SportAssociationManagerComponents";
}



@{
    ViewBag.Title = "SportAssociationManagerComponents";
}

<body style="font-size:20px">

    <h1>Sport Association Manager Components</h1>

    <hr />

    <h2>Choose what you want to do!</h2>

    <br />



    @Html.ActionLink("Add New Match", "AddNewMatch", "SportManager")

    <br />
    @Html.ActionLink("Delete Match", "DeleteMatch", "SportManager")

    <br />
    @Html.ActionLink("View All Upcoming Matches", "AllComingMatches", "SportManager")

    <br />
    @Html.ActionLink("View Already Played Matches", "AllPlayedMatches", "SportManager")

    <br />
    @Html.ActionLink("View Clubs Never Matched", "ClubsNeverMatched", "SportManager")

    <br />
    @Html.ActionLink("View All Matches", "AllMatches", "SportManager")

    <br />
    @Html.ActionLink("Show all clubs in the system", "AllClubs", "SportManager")

</body>