Models/Fan.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerWebsite.Models
{
    public class Fan
    {

        public String name { get; set; }
        public String username { get; set; }
        public String nationalId { get; set; }
        public String phoneNumber { get; set; }
        public String address { get; set; }
        public String birthDate { get; set; }
        public String status { get; set; }


        public Fan(string name, string username, string nationalId, string phoneNumber, string address, string birthDate, string status)
        {
            this.name = name;
            this.username = username;
            this.nationalId = nationalId;
            this.phoneNumber = phoneNumber;
            this.address = address;
            this.birthDate = birthDate;
            this.status = status;
        }

    }
}

Models/Message.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SoccerWebsite.Models
{
    public class Message
    {
        public String content { get; set; }

        public Message(String content)
        {
            this.content = content;
        }
    }
}

Controllers/FanController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using System.Web.UI.WebControls;
using SoccerWebsite.Models;
using System.Web.Http.Results;

namespace SoccerWebsite.Controllers
{
    public class FanController : Controller
    {
        SqlConnection connection = new SqlConnection(ConfigurationManager.ConnectionStrings["Soccer"].ToString());
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Login()
        {
             return View();

        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult InputDate()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            return View();
        }


        public ActionResult AllTickets()
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            connection.Open();

            SqlCommand cmd2 = new SqlCommand();
            cmd2.Connection = connection;
            cmd2.CommandText = "select * from dbo.getAllTickets('" + Session["newUser"].ToString() + "')";

            SqlDataReader dr = cmd2.ExecuteReader();

            List<Ticket> allTickets = new List<Ticket>();

            while (dr.Read())
            {
                Ticket ticket = new Ticket(dr["fanName"].ToString(), dr["hostName"].ToString(), dr["guestName"].ToString(), dr["starts"].ToString(), dr["stadName"].ToString());

                allTickets.Add(ticket);
            }

            connection.Close();
            return View("AllTickets", allTickets);
        }

        [HttpPost]
        public ActionResult Login(String username, String password,String id)
        {


            SqlCommand cmd = new SqlCommand("fanLogIn", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));
            cmd.Parameters.Add(new SqlParameter("@fan_id", id));


            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = id;
                return View ("FanComponents");

            }
            else
            {
                Message msg = new Message("You are not registered, Please create an account or you are blocked from using the system");
                return View("Message", msg);
            }

        }
        [HttpPost]
        public ActionResult Register(String fanName, String nationalId, String password, String username,String phoneNumber,String birthdate,String address)
        {

            try
            {
                if (!(birthdate[2].ToString().Equals("/") && birthdate[5].ToString().Equals("/")) || birthdate.Length != 10)
                {
                    Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                    return View("Message", msg);
                }
                else
                {
                    int month = Int32.Parse(birthdate[0] + "" + birthdate[1]);
                    int day = Int32.Parse(birthdate[3] + "" + birthdate[4]);

                    if (month > 12 || month < 1 || day > 30 || day < 1)
                    {
                        Message msg = new Message("Please enter a valid date format Month/Day/Year");
                        return View("Message", msg);
                    }
                }
            }
            catch (Exception e)
            {
                Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                return View("Message", msg);
            }

            SqlCommand cmd = new SqlCommand("addFan", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            cmd.Parameters.Add(new SqlParameter("@name", fanName));
            cmd.Parameters.Add(new SqlParameter("@national_id_number", nationalId));
            cmd.Parameters.Add(new SqlParameter("@username", username));
            cmd.Parameters.Add(new SqlParameter("@password", password));
            cmd.Parameters.Add(new SqlParameter("@address", address));
            cmd.Parameters.Add(new SqlParameter("@phone_number", phoneNumber));
            cmd.Parameters.Add(new SqlParameter("@birth_date", birthdate));



            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;


            connection.Open();
            cmd.ExecuteNonQuery();
            connection.Close();

            if (result.Value.ToString().Equals("1"))
            {
                Session["newUser"] = nationalId;
                return View("FanComponents");
            }
            else
            {
                Message msg = new Message("There is a user exists already with that username");
                return View("Message", msg);
            }

        }
        [HttpPost]
        public ActionResult AvailableMatches(String date)
        {

            

            connection.Open();
            

            SqlCommand cmd2 = new SqlCommand();
            cmd2.Connection = connection;
            cmd2.CommandText = "select * from dbo.viewAllMatches('" + date + "')";

            SqlDataReader dr = cmd2.ExecuteReader();

            List<Match> allMatches = new List<Match>();

            while (dr.Read())
            {
                Match match = new Match(dr["hostName"].ToString(), dr["guestName"].ToString(), dr["starts"].ToString(), null,dr["stadName"].ToString(), dr["location"].ToString());

                allMatches.Add(match);
            }

            connection.Close();
            return View("AvailableMatches", allMatches);

        }
        public ActionResult PurchaseTicket(String hostName, String guestName, String start)
        {
            if (Session["newUser"] == null)
            {
                Message msg = new Message("You are not logged in");
                return View("Message", msg);
            }
            try
            {
                if (!(start[2].ToString().Equals("/") && start[5].ToString().Equals("/")) || start.Length != 10)
                {
                    Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                    return View("Message", msg);
                }
                else
                {
                    int month = Int32.Parse(start[0] + "" + start[1]);
                    int day = Int32.Parse(start[3] + "" + start[4]);

                    if (month > 12 || month < 1 || day > 30 || day < 1)
                    {
                        Message msg = new Message("Please enter a valid date format Month/Day/Year");
                        return View("Message", msg);
                    }
                }
            }
            catch (Exception e)
            {
                Message msg = new Message("Please enter a valid date format for Month/Day/Year");
                return View("Message", msg);
            }

            String newFormatString = start[3] + "" + start[4] + "/" + start[0] + "" + start[1] + "/" + start.Substring(6, 4);

            SqlCommand cmd = new SqlCommand("purchaseTicket", connection);
            cmd.CommandType = System.Data.CommandType.StoredProcedure;

            DateTime startTime = DateTime.ParseExact(newFormatString, "MM/dd/yyyy", null);

            SqlParameter result = cmd.Parameters.Add("@result", SqlDbType.Int);
            result.Direction = ParameterDirection.Output;

            cmd.Parameters.Add(new SqlParameter("@national_id", Session["newUser"].ToString()));
            cmd.Parameters.Add(new SqlParameter("@host_club_name", hostName));
            cmd.Parameters.Add(new SqlParameter("@guest_club_name", guestName));
            cmd.Parameters.Add(new SqlParameter("@start_time", startTime));



            connection.Open();
            cmd.ExecuteNonQuery();

            connection.Close();
            if (result.Value.ToString().Equals("1"))
            {
             
                return RedirectToAction("AllTickets");

            }
            else
            {
                Message msg = new Message("Failed to purchase, you are blocked or no tickets avilable");
                return View("Message", msg);
            }

        }










    }

}

Views/Fan/AllTickets.cshtml
@{
    ViewBag.Title = "AllTickets";
}

<h1>All Tickets</h1>

@model List<SoccerWebsite.Models.Ticket>


<hr />

<table class="table table-striped">
    <thead>
        <tr>

            <th scope="col">Fan Name</th>
            <th scope="col">Host Club Name</th>
            <th scope="col">Guest Club Name</th>
            <th scope="col">Start Time</th>
            <th scope="col">Stadium Name</th>
        </tr>
    </thead>
    <tbody>
        @foreach (SoccerWebsite.Models.Ticket ticket in Model)
        {
            <tr>
                <td>@ticket.fanName</td>
                <td>@ticket.hostName</td>
                <td>@ticket.guestName</td>
                <td>@ticket.starts</td>
                <td>@ticket.stadName</td>

            </tr>
        }
    </tbody>
</table>

Views/Fan/AvailableMatches.cshtml
@{
    ViewBag.Title = "AvailableMatches";
}

<h1>Available Matches</h1>

@model List<SoccerWebsite.Models.Match>


<hr />

<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Host Club Name</th>
            <th scope="col">Guest Club Name</th>
            <th scope="col">Stadium Name</th>
            <th scope="col">Location</th>
            <th scope="col">Purchase</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var match in Model)
        {
            <tr>
                <td>@match.hostName</td>
                <td>@match.guestName</td>
                <td>@match.stadiumName</td>
                <td>@match.location</td>


                <td>
                    <button class="btn btn-success">
                        @Html.ActionLink("PurchaseTicket", "PurchaseTicket", new { @hostName = match.hostName, @guestName = match.guestName, @start = match.starts })

                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>

Views/Fan/FanComponents.cshtml
@{
    ViewBag.Title = "FanComponents";
}


<body style="font-size:20px">

    <h1>Fan Components</h1>

    <hr />

    <h2>Choose what you want to do!</h2>

    <br />



    @Html.ActionLink("View Available Matches", "InputDate", "Fan")

    <br />

    @Html.ActionLink("Show your tickets", "AllTickets", "Fan")






</body>

Views/Fan/InputDate.cshtml
@{
    ViewBag.Title = "InputDate";
}

<h1>Select Date</h1>

<hr />

@using (Html.BeginForm("AvailableMatches", "Fan", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Date</label>
            <input type="text" placeholder="MM/DD/YY" class="form-control" id="exampleInputUsername" name="date" required>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/Fan/Login.cshtml
@{
    ViewBag.Title = "LogIn";
}

<h1>LogIn</h1>

<hr />

@using (Html.BeginForm("Login", "Fan", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="exampleInputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="exampleInputUsername" name="username" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="exampleInputPassword" name="password" required>
        </div>
        <br />
        <br />
        <div class="mb-3">
            <label for="exampleInputPassword" class="form-label">National Id</label>
            <input type="text" class="form-control" id="exampleInputPassword" name="id" required>
        </div>
        <br />

        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}

Views/Fan/Message.cshtml
@model SoccerWebsite.Models.Message

@{
    ViewBag.Title = "Message";
}



<body style="text-align:center;color:red;display:flex;justify-content:center">

    <h1 style="color:black">Something went wrong</h1>
    <br />
    <div style="border:2px solid red;padding:20px 20px 50px 20px">
        <h2>@Model.content</h2>
    </div>

</body>

Views/Fan/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h1>Fan Register</h1>
<hr />


@using (Html.BeginForm("Register", "Fan", FormMethod.Post))
{
    <form>
        <div class="mb-3">
            <label for="inputName" class="form-label">Fan Name</label>
            <input type="text" class="form-control" id="inputName" name="fanName" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputName" class="form-label">National Id</label>
            <input type="text" class="form-control" id="inputName" name="nationalId" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputUsername" class="form-label">Username</label>
            <input type="text" class="form-control" id="inputUsername" name="username" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputPassword" class="form-label">Password</label>
            <input type="password" class="form-control" id="inputPassword" name="password" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputPassword" class="form-label">Phone Number</label>
            <input type="text" class="form-control" id="inputPassword" name="phoneNumber" required>
        </div>
        <br />
        <div class="mb-3">
            <label for="inputPassword" class="form-label">Birth Date</label>
            <input type="text" placeholder="MM/DD/YYYY" class="form-control" id="inputPassword" name="birthdate" required>
        </div>
        <br />
        <br />
        <div class="mb-3">
            <label for="inputPassword" class="form-label">Address</label>
            <input type="text" class="form-control" id="inputPassword" name="address" required>
        </div>
        <br />
        <button type="submit" class="btn btn-primary">Submit</button>
        <br />
    </form>
}